#!/usr/bin/env babel-node

import {readFileSync} from 'fs';

import minimist from 'minimist';

import balance from './dist/balance';
import readTransactionsFromFile from './dist/read-transactions-from-file';
import csvDisplay from './dist/display-csv';
import tableDisplay from './dist/display-table';

const argv = minimist(process.argv.slice(2));
const csvFileName = argv._[0];

const transactions = readTransactionsFromFile(csvFileName);
const results = balance(transactions);

switch (argv.out) {
case 'csv':
  csvDisplay(results);
  break;
case 'table':
default:
  tableDisplay(results);
}
